#!/bin/bash
# Source this to load the full environment that hutch python uses

# edit these lines only
USE_LOCAL="1"
export CONDA_ENVNAME="pcds-4.0.1"
#export CONDA_ENVNAME="dev"

export HUTCH="xcs"
export LOCAL_BASE="/u1/xcsopr/conda_envs"
export NFS_BASE="/reg/g/pcds/pyps/conda/py36"

if [ -n "${USE_LOCAL}" ] && [ -d "${LOCAL_BASE}" ]; then
  echo "Loading local disk python env ${CONDA_ENVNAME}"
  source "${LOCAL_BASE}/${CONDA_ENVNAME}/bin/activate"
else
  echo "Loading NFS python env ${CONDA_ENVNAME}"
  source "${NFS_BASE}/etc/profile.d/conda.sh"
  conda activate "${CONDA_ENVNAME}"
fi

unset PYTHONPATH
unset LD_LIBRARY_PATH

HERE=`dirname $(readlink -f $BASH_SOURCE)`

if [ -f "${HERE}/../common/dev/hutch-python/bin/hutch-python" ]; then
    export PATH="${HERE}../common/dev/hutch-python/bin:${PATH}"
fi

export PYTHONPATH="${HERE}:${HERE}/dev/devpath:${HERE}/../common/dev/devpath"
source pcdsdaq_lib_setup
export CONDA_PROMPT_MODIFIER="(${HUTCH}-${CONDA_ENVNAME})"
