#!/bin/bash
# Source this to load the full environment that hutch python uses

# edit this line only
export CONDA_ENVNAME="pcds-3.3.3"
#export CONDA_ENVNAME="dev"
export CONDA_BASE="/reg/g/pcds/pyps/conda/py36"
export HUTCH="xcs"

unset PYTHONPATH
unset LD_LIBRARY_PATH

source "${CONDA_BASE}/etc/profile.d/conda.sh"
conda activate "${CONDA_ENVNAME}"
HERE=`dirname $(readlink -f $BASH_SOURCE)`

if [ -f "${HERE}/../common/dev/hutch-python/bin/hutch-python" ]; then
    export PATH="${HERE}../common/dev/hutch-python/bin:${PATH}"
fi

export PYTHONPATH="${HERE}:${HERE}/dev/devpath:${HERE}/../common/dev/devpath"
source pcdsdaq_lib_setup
export CONDA_PROMPT_MODIFIER="(${HUTCH}-${CONDA_ENVNAME})"
